<!DOCTYPE html>
<html lang="en" class="header-align-center">
	<head>
		<title>Carwalla</title>

		<?php include 'includes/header.php'; ?>

		<div class="content" id="content">

			<div class="box-wr box-heading-sm text-center bg-gradient-blue">
				<div class="container wow fadeIn" data-wow-delay="0.2s">
					<h1 class="color-brick">Terms of Use Agreement</h1>
					<h5><em>Last Updated: January 1, 2020</em></h5>
				</div><!-- END of .container -->
			</div><!-- END of .box-wr -->

			<div class="box-wr box-text text-left bg-white">
				<div class="container wow fadeIn" data-wow-delay="0.2s">



<span class="tdu"><strong>Terms of Use Agreement</strong></span></p>
<p>You are visiting a website owned by LendingTree, LLC. By using this website, you are entering into a legal agreement to abide by the terms of use you see here, and you are agreeing that you have read and fully understand these terms of use.</p>
<p>This Terms of Use Agreement (“Agreement”) applies to the websites operated by LendingTree, LLC and any of its affiliates and subsidiaries (“Websites” or each individually “Website”) on which this Agreement is displayed. This Agreement also applies to your use of any goods, facilities or services offered through the Websites (collectively “Services”), regardless of how they are accessed. By accessing, browsing, or using the Websites, you acknowledge that you understand, accept and agree to be bound by this Agreement, as well as our <a href="https://www.lendingtree.com/legal/privacy-policy/">Privacy Policy,</a> which is incorporated into this Agreement by reference. You agree that, to the fullest extent required by the law of any state, you have been provided with, have received, and are agreeing to all disclosure and consent requirements. Certain Services may include additional terms; by agreeing to proceed with any such Services you acknowledge that you have read, understand, and agree to be bound by any additional terms displayed or referenced that apply to that Service.</p>
<ul>
	<li>For purposes of this Agreement, &#8220;you&#8221; or &#8220;your&#8221; means the person(s) using the Websites and/or the Services, and any person(s) for whom such person(s) are acting as an agent with respect to the Websites and/or the Services.</li>
	<li>&#8220;LendingTree&#8221;, &#8220;us&#8221; or &#8220;we&#8221; includes LendingTree, LLC and any of its affiliates or subsidiaries.</li>
	<li>“Loan” includes, but may not be limited to, any of the credit and related products and services which you inquire about by using the LendingTree websites.</li>
	<li>“Provider(s)” includes, but may not be limited to, the banks, lenders, financial institutions, insurers, service providers, real estate companies, dealers, agents, brokers and other entities offering products and services through LendingTree&#8217;s Websites.</li>
	<li>“Qualification Form” refers to your request to be matched with providers of any of the products and services that you may be connected to through LendingTree’s Websites.</li>
</ul>
<ol></ol>
<p>We are licensed as set forth in the <a href="https://www.lendingtree.com/legal/licenses-and-disclosures/">Licenses and Disclosures section</a>, which is incorporated into this Agreement by reference.</p>
<p>We reserve the right, at our sole discretion, to change or modify the Websites or this Agreement (or any portion thereof) at any time. Such changes and modifications become effective immediately upon posting on the Websites. You agree to review this Agreement for any such changes upon your use of the Websites and that your continued use of the Websites or Services constitutes your acceptance of such changes and modifications. The Websites are intended for individuals who are at least 18 years of age and are accessing the internet from a physical location within the United States of America. By using or accessing the Websites, you acknowledge that you are 18 years of age or older and are accessing the internet from a physical location within the United States of America.</p>
<p><em><span class="tdu">Privacy Policy<br />
	</span></em><br />
	Our <a href="https://www.lendingtree.com/legal/privacy-policy/">Privacy Policy</a>, hereby incorporated by reference into this Agreement, explains how We collect, protect, share, and use your information as part of our technology platforms, and all of our products and services.
</p>
<p><span class="tdu"><em>Consumer Information Security Policy<br />
	</em></span><br />
	Our <a href="https://www.lendingtree.com/legal/security/">Consumer Information Security Policy</a>, hereby incorporated by reference into this Agreement, explains the measures we take to protect your information and descriptions of ways we implement these measures for different types of information you may provide to us.
</p>
<p><span class="tdu"><em>Electronic Communications/Notices and Information Delivered Electronically<br />
	</em></span><br />
	Our <span class="tdu">Consent Agreement for Electronic Disclosures and Communications</span>, hereby incorporated by reference into this Agreement, explains your agreement to receive all current and future notices, disclosures, communications and information, and to do business electronically with us and our Providers. Your continued use of this site is evidence of your acceptance and agreement to be bound by this Agreement.
</p>
<p><span class="tdu"><em>Copyright, Trademark and Service Mark Notices</em></span></p>
<p>All text, graphics, photographs, videos, sound, trademarks, logos, artwork, interfaces and computer code, including but not limited to the design, coordination, “look and feel” and arrangement of elements contained on the Websites (collectively “Content”) is owned or licensed by or to LendingTree. The Content is protected by trademark, copyright, and patent laws, and other intellectual property rights and unfair competition laws. Except as expressly stated herein, no part of the Websites or Content may be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, transmitted or distributed in any way, including the use of framing or mirrors, to any other computer, server, website or other medium for publication or distribution or for any commercial enterprise, without LendingTree’s prior written permission. Nothing on the Websites should be construed as granting any license or right to use any Content.</p>
<p><span class="tdu"><em>Disclaimers and Liability</em></span></p>
<p>THE WEBSITES, CONTENT AND SERVICES ARE PROVIDED FOR USE “AS IS” WITHOUT WARRANTY OF ANY KIND. LENDINGTREE DOES NOT WARRANT THAT THE WEBSITES, CONTENT OR SERVICES WILL BE ACCURATE, ERROR-FREE OR UNINTERRUPTED. LENDINGTREE DOES NOT WARRANT THAT THE WEBSITES, CONTENT OR SERVICES WILL PROVIDE SPECIFIC RESULTS.</p>
<p>TO THE MAXIMUM EXTENT NOT PROHIBITED BY LAW:</p>
<ul>
	<li>UNDER NO CIRCUMSTANCES WILL LENDINGTREE BE LIABLE FOR ANY DAMAGES WHATSOEVER ARISING OUT OF YOUR RELIANCE ON OR USE OF THE WEBSITES, CONTENT, SERVICES OR OTHER ITEMS LOCATED ON THE WEBSITES.</li>
	<li>LENDINGTREE DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER STATUTORY, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.</li>
</ul>
<ol></ol>
<p>ADDITIONALLY, THE INCLUSION OR OFFERING OF ANY PRODUCTS OR SERVICES ON THE WEBSITES DOES NOT CONSTITUTE ANY ENDORSEMENT OR RECOMMENDATION OF SUCH PRODUCTS OR SERVICES BY US. ALL SUCH INFORMATION, PRODUCTS AND SERVICES ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY KIND.</p>
<p><span class="tdu"><em>Indemnity</em></span></p>
<p>You agree to indemnify, defend and hold harmless LendingTree and its officers, directors, shareholders, predecessors, successors-in-interest, licensors, employees, agents, subsidiaries and affiliates (“Lending Tree Parties”), from and against any and all claims, losses, liabilities, expenses (including attorneys&#8217; fees and costs) and damages arising out of or relating to your use of the Websites or Services, your violation of any third-party right or law, or your violation or alleged violation of this Agreement. You must not settle any such claim or matter without the prior written consent of LendingTree. The LendingTree Parties reserve the right, at their own expense, to assume the exclusive defense and control of any matter subject to indemnification by you, and you further agree that you will cooperate fully in the defense of any such claims.</p>
<p><span class="tdu"><em>Limitation on Damages</em></span></p>
<p>LENDINGTREE’S LIABILITY, IF ANY, SHALL BE LIMITED TO DIRECT AND FORESEEABLE DAMAGES, WHICH SHALL NOT EXCEED THE AMOUNT PROVIDED BELOW. UNDER NO CIRCUMSTANCES SHALL LENDINGTREE BE LIABLE FOR INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, STATUTORY, PUNITIVE OR EXEMPLARY DAMAGES SUCH AS, BUT NOT LIMITED TO, LOSS OF REVENUE OR ANTICIPATED PROFITS OR LOST BUSINESS, LOSS OF OR DAMAGE TO DATA, OR EMOTIONAL DISTRESS NOTWITHSTANDING ANY OTHER PROVISION OF THIS AGREEMENT, IN NO EVENT SHALL LENDINGTREE’S TOTAL LIABILITY EXCEED U.S. $100.00. THESE LIMITATIONS AND EXCLUSIONS APPLY EVEN IF THIS REMEDY DOES NOT FULLY COMPENSATE YOU FOR ANY LOSSES OR FAILS OF ITS ESSENTIAL PURPOSE OR IF WE KNEW OR SHOULD HAVE KNOWN ABOUT THE POSSIBILITY OF THE DAMAGES. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THESE LIMITATIONS AND EXCLUSIONS APPLY TO ANY CLAIMS RELATED TO THIS AGREEMENT OR TO THE SERVICES.</p>
<p><em><span class="tdu">Links to Third Party Websites</span><br />
	</em><br />
	The Websites may contain links to websites maintained by third parties. Such links are provided for your convenience and reference only. We do not operate or control in any respect any information, software, products or services available on non-affiliated third-party websites. Our inclusion of a link to a website does not imply any endorsement of the services or the website, its contents, or its sponsoring organization. Your use of any such third-party websites may be subject to other terms and conditions imposed by the third parties maintaining those websites. When you leave the Websites, you agree that We are not responsible for the accuracy or content of the information provided by that website, nor is it liable for any direct or indirect technical or system issues arising out of your access to or use of third-party technologies or programs available through that website.
</p>
<p><span class="tdu"><em>Errors and Delays</em></span></p>
<p>You agree that LendingTree is not responsible for any errors or delays in responding to a request or referral form caused by, including but not limited to, an incorrect email address or other information provided by you or other technical problems beyond our reasonable control.</p>
<p><span class="tdu"><em>Dispute Resolution, Governing Law, Waivers and Limitations</em></span></p>
<p>YOU AGREE THAT ANY DISPUTE BETWEEN YOU AND US, INCLUDING WITHOUT LIMITATION DISPUTES RELATING TO THE WEBSITES, CONTENT OR SERVICES (“DISPUTE”), SHALL BE FINALLY AND EXCLUSIVELY RESOLVED BY BINDING INDIVIDUAL ARBITRATION ADMINISTERED BY THE AMERICAN ARBITRATION ASSOCIATION (“AAA”) IN ACCORDANCE WITH ITS CONSUMER ARBITRATION RULES. DISPUTES WILL BE ARBITRATED AT A HEARING CONDUCTED IN CHARLOTTE, NORTH CAROLINA; THE ARBITRATOR(S) SHALL HAVE NO AUTHORITY TO DEVIATE FROM THE LAW, AND THE ARBITRATOR(S) SHALL MAKE ALL REASONABLE EFFORTS TO EXPEDITE THE ARBITRATION PROCEEDINGS AND TO LIMIT DISCOVERY. <strong>THIS MEANS THAT YOU WILL NOT BE ABLE TO LITIGATE ANY SUCH DISPUTE IN COURT, AND THAT YOU AGREE TO WAIVE YOUR RIGHT TO A JURY TRIAL.</strong> YOU AGREE THAT ANY DISPUTE WILL BE GOVERNED BY THE LAWS OF THE STATE OF NORTH CAROLINA WITHOUT REGARD TO ANY CONFLICTS OF LAWS PROVISIONS. IF ANY MATTER PROCEEDS IN COURT, INCLUDING POST-ARBITRATION CONFIRMATION PROCEEDINGS, YOU AGREE TO THE EXCLUSIVE PERSONAL JURISDICTION BY, AND VENUE IN, THE STATE AND FEDERAL COURTS LOCATED IN MECKLENBURG COUNTY, NORTH CAROLINA, AND WAIVE ANY OBJECTION TO SUCH JURISDICTION OR VENUE.</p>
<p>You agree that no arbitration under this agreement shall be joined to an arbitration involving any other party subject to this agreement. Arbitration must be on an individual basis. You may not join or consolidate claims in arbitration or litigate in court or arbitrate any claims as a representative or member of a class or in a private attorney general capacity.</p>
<p>You agree that any dispute or disagreement regarding the enforceability, applicability or interpretation of any provision of this Agreement, including the provisions regarding dispute resolution and arbitration, is a Dispute subject to the arbitration provisions herein and shall be resolved by an arbitrator.</p>
<p>You also agree that any dispute or cause of action arising out of or related to the Websites, Services or Content must be commenced within one year from the later of (1) when the dispute or cause of action accrues or, (2) through the exercise of reasonable diligence you should have known about the accrual of the cause of action. Otherwise, such cause of action is permanently barred.</p>
<p>This Agreement (including all referenced or incorporated policies, agreements and other provisions) constitutes the entire agreement between you and LendingTree and supersedes all prior or contemporaneous oral or written agreements or other communications between the parties with respect to the subject matter hereof. If a conflict between the language of this Terms of Use Agreement and the language of any terms incorporated by reference, the latter incorporated terms shall control.</p>
<p>You acknowledge and agree that, in entering into this Agreement, you are not relying on any representation, warranty, statement or promise, express or implied, not explicitly set forth in this Agreement, and you hereby waive any claimed reliance on same. If any provision of this Agreement shall be found to be invalid or unenforceable, you agree such provision shall, to the maximum extent feasible, be modified by to render it enforceable with respect to the Dispute at issue and to reflect to the maximum extent possible the intent of the existing language of the provision when considered in the context of this Agreement as a whole, that such modified provision shall be enforced with respect to the underlying claims in the Dispute at issue, and that such a finding of invalidity or unenforceability shall not affect the validity or enforceability of this Agreement as a whole or of any other provision of this Agreement.</p>
<p><strong><span class="tdu">Terms Applicable to All Services</span></strong></p>
<p>We provide educational content and operate online marketplaces that enable consumers to comparison shop on LendingTree’s Websites for financial products and services offered by LendingTree’s network of Providers.</p>
<p><strong>By submitting any Qualification Form containing your electronic signature through a LendingTree Website, and separately for each such request you submit, you are indicating that you desire to be contacted by Providers, and you are providing express written consent that LendingTree, a third party on LendingTree’s behalf, and LendingTree’s Network Partners with whom you are matched, may deliver calls or text messages to you, including for marketing purposes, using an automatic telephone dialing system or an artificial or prerecorded voice to the phone number you have provided. You understand that you are providing this consent to receive such telephone calls even if your telephone number is currently listed on any federal, state, local, internal, or corporate Do-Not-Call (“DNC”) Lists. You understand that you are not required to consent to receive these communications as a condition of using LendingTree’s services.</strong></p>
<p>You consent to receive email from LendingTree, its affiliates, and its Providers at the email address you provided or at other addresses that may be associated with you that we receive from Providers or other parties. You hereby consent to any such email, so it will not be considered spam or unauthorized by any local, state or federal law or regulation. You agree that the consents described herein shall remain valid and in effect until you revoke them by opting out as described below.</p>
<p><strong>You may opt out of receiving calls from LendingTree</strong> at any time by engaging in any of the following reasonable means: (1) emailing <a href="mailto:privacy@lendingtree.com">privacy@lendingtree.com</a> to expressly state in writing that you no longer wish to be contacted by LendingTree and are revoking your consent to be contacted; (2) notifying a LendingTree customer service representative that you no longer wish to be contacted by LendingTree and are revoking your consent to be contacted; or (3) Responding to any SMS, mobile, or text message you receive from LendingTree in accordance with the express written instructions of that particular messaging program. At any time, you may update your preferred method of contact by calling 1-888-272-1355. You agree to notify any particular Provider directly if you no longer want to receive communications from them. You further agree that LendingTree is not responsible for a Provider’s failure to follow your or our instructions to stop contacting you.</p>
<p><strong>LendingTree is not a lender or a creditor.</strong> LendingTree is not an agent of either you or any Provider. Except as otherwise provided for in your state (please see the Licenses section of the Websites), LendingTree is not acting as your agent or as the agent of any Provider. LendingTree’s services are only administrative. You agree you will rely on your own judgment and research independent of any communications or information you receive from LendingTree in deciding which available product, terms and Provider best suits your needs and financial situation.</p>
<p>Any Qualification Form you submit is not an application for credit. Rather, it is an inquiry to be matched with Providers that may be able to present conditional offers. <strong>Some Automobile Finance Providers, however, may provide firm offers.</strong> The Provider is solely responsible for its services to you, and you agree that LendingTree shall not be liable for any damages or costs of any type arising out of or in any way connected with your use of such services or your interactions with any Provider. You understand that Providers may keep your Qualification Form information and any other information provided by LendingTree or received by them in the processing of your Qualification Form, whether you are qualified for a product with them or complete a formal application for services with them.</p>
<p>For any Service, by saving your information with LendingTree or submitting a Qualification Form, you represent that all the information you have provided is true, accurate, current and complete. You further acknowledge that you alone will use your account to access the Services. You must not sell, transform or assign your account to anyone else. You agree to keep your login information confidential, to employ reasonable and appropriate safeguards to prevent unauthorized access to your account, and to not share your account credentials with any third party or allow anyone else to log into our Services as you. You are responsible for all activities that occur under your member account. If you believe that your account is no longer secure, you agree to notify us immediately.</p>
<p>When you &#8220;submit&#8221; information, create an account or otherwise register for Services through our Websites, you understand and agree that you have established a business relationship between you and LendingTree. Accordingly, LendingTree may send your information to certain affiliates and third parties as provided in the <a href="https://www.lendingtree.com/legal/privacy-policy/">Privacy Policy</a> and you agree that LendingTree, its affiliates, and persons calling on LendingTree’s behalf may contact you using information you provided with information and offers of services available through LendingTree and the Websites. You also give LendingTree permission to retain all such provided information and to make live or recorded calls to discuss, provide or remind you of any information regarding your submission, including incomplete Qualification Forms, the identification of matched Providers, deadlines, quality of services or other matters in connection with your Qualification Form.<br />
	In addition, certain state and federal laws require that the information you provide us is housed and securely maintained and cannot be removed, purged, or destroyed until the expiration of certain prescribed periods. Providers may also from time-to-time be required to share the information you submit to them with LendingTree in order to adhere to applicable laws. Providers and LendingTree may also maintain and share information provided by you and about you by third parties for internal marketing and analytics. You are providing express written consent for the retention of this information upon completion of an inquiry form for LendingTree and the selected Provider to share this information for these purposes.
</p>
<p>By submitting a Qualification Form, you are providing express written instructions under the Fair Credit Reporting Act <strong>for LendingTree and Provider partners with whom you are matched to obtain your consumer credit report from your credit profile or other information from contracted Credit Bureau(s) for the purpose of matching you to a Provider, product, or service through the LendingTree network.</strong> This information could include, but might not be limited to, your credit report, credit score, and other credit information. LendingTree will obtain a limited credit report (“soft pull”) regardless of whether you provide your Social Security Number. To help the government fight identity theft, the funding of terrorism and money laundering activities, and to help attempt to verify your identity, LendingTree and its Providers may obtain, verify and record information that identifies each person who opens an account with us and Providers. LendingTree and its Providers may ask for your name, Social Security Number, address, telephone number, date of birth and other important information including, but not limited to, information received from your credit file, that may allow us and Providers to properly identify you. It is possible that a Provider may perform a soft inquiry on your credit at the same time for the same or similar purposes, but the soft inquiry into your credit does not impact your credit score. Not all Providers will receive your Social Security Number and, for those that do, not all will perform the soft inquiry of credit. <strong>LendingTree does not perform hard inquiries into credit, though certain automobile lenders on its network will perform a hard inquiry to evaluate you for a firm offer of credit.</strong> From time-to-time LendingTree is examined by state and federal regulators and as such is required to maintain your Personally Identifiable Information to adhere to certain jurisdictions’ data retention requirements. Your information may also be obtained from Providers after you are matched to adhere to state and federal reporting and record retention requirements. You authorize LendingTree and its participating Providers to share such information as required.</p>
<p>Services offered by Providers may only be made to residents of states where Providers are authorized to make such Loans. A Provider’s participation in and offering of its products on the Websites does not constitute an offer by any Provider or by LendingTree to provide services outside of their authorized jurisdictions, and to the extent you seek or receive information from a Provider regarding any prospective service which would be outside of the Providers’ authorized jurisdiction, that information is for informational purposes only. Providers shall have the right to discontinue, suspend or terminate the offering of any Loan product in any specific state through the Websites at any time, without prior notice.</p>
<p>We do not guarantee acceptance into any particular program or specific terms or conditions with any Provider; approval standards are established and maintained solely by individual Providers. Likewise, we do not guarantee that the rates offered by Providers include the lowest rates available in the market or the rate that the Providers will ultimately charge. A Provider&#8217;s conditional Loan offer may be subject to market conditions, approval and qualification. The rates and fees actually provided by Providers may be higher or lower depending on your complete credit profile, collateral/property considerations (if applicable) including but not limited to location, equity and value and income/asset consideration including but not limited to Loan to value and debt to income ratios. Unless expressly stated in writing, nothing contained herein shall constitute an offer or promise for a Loan commitment or interest rate lock-in agreement. Providers may not offer all products as well as not offer products in all states. You might not be matched with the Provider making any specific offer. If you agree to terms with any Provider with whom you are matched on our Websites, you will be responsible for paying for any closing costs associated with your Loan (such as settlement services, Loan processing, underwriting or funding fees) at closing.</p>
<p>By clicking on any button indicating an acceptance or agreement to terms, a continuance of processing or submission (collectively, a &#8220;submission&#8221;) you understand that you are consenting, acknowledging and agreeing to the stated terms and conditions of that submission and that you are submitting an inquiry for a Service through LendingTree to each of the Providers to whom your Loan request is transmitted. You are also indicating that you are consenting, acknowledging and agreeing to receive notices, disclosures and other communications (&#8220;Disclosures and Communications&#8221;) in electronic form (either by email or via the Internet) as provided for in the <a href="https://www.lendingtree.com/legal/network-lenders-consent/">Consent for Electronic Disclosures and Communications</a> from LendingTree and its Providers.</p>
<p><span class="tdu">Terms Applicable to Financial Education Content</span></p>
<p>We provide content and tools on our Websites that allow you to enhance your financial education and learn how certain financial decisions could impact your financial well-being. We provide these materials for informational, educational, and entertainment purposes only, and at no time are we providing legal, financial, investment, tax planning, or medical advice. You may see offers on these Websites from companies that compensate us. This compensation may impact the location and order in which these offers appear. Our Websites do not include the entire universe of available credit or financial offers.</p>
<p><span class="tdu">Ratings &amp; Reviews and User-Generated Content</span></p>
<p>On certain LendingTree Websites, you may submit user generated content. By submitting any content on these Websites or through any social media channel associated with LendingTree, you represent and warrant that:</p>
<ul>
	<li>you are the sole author and owner of the intellectual property rights thereto;</li>
	<li>all “moral rights” that you may have in such content have been voluntarily waived by you;</li>
	<li>all content that you post is accurate;</li>
	<li>you are at least 13 years old; and</li>
	<li>use of the content you supply does not violate this Agreement and will not cause injury to any person or entity.</li>
</ul>
<ol></ol>
<p>You further agree and warrant that you shall not submit any content:</p>
<ul>
	<li>that is known by you to be false, inaccurate or misleading;</li>
	<li>that infringes any third party’s copyright, patent, trademark, trade secret or other proprietary rights or rights of publicity or privacy;</li>
	<li>that violates any law, statute, ordinance or regulation (including, but not limited to, those governing export control, consumer protection, unfair competition, anti-discrimination or false advertising);</li>
	<li>that is, or may reasonably be considered to be, defamatory, libelous, hateful, racially or religiously biased or offensive, unlawfully threatening or unlawfully harassing to any individual, partnership or corporation;</li>
	<li>for which you were compensated or granted any consideration by any third party;</li>
	<li>that includes any information that references other websites, addresses, email addresses, contact information or phone numbers; or</li>
	<li>that contains any computer viruses, worms or other potentially damaging computer programs or files.</li>
</ul>
<ol></ol>
<p>You agree to indemnify and hold LendingTree (and its officers, directors, agents, subsidiaries, joint ventures, employees and third-party service providers), harmless from all claims, demands, and damages (actual and consequential) of every kind and nature, known and unknown including reasonable attorneys’ fees, arising out of a breach of your representations and warranties set forth above, this Agreement, or your violation of any law or the rights of a third party.</p>
<p>For any content that you submit on the Websites, Facebook, Twitter or any similar LendingTree-affiliated social media property, you grant LendingTree a perpetual, irrevocable, royalty-free, transferable right and license to use, copy, modify, delete in its entirety, adapt, publish, translate, create derivative works from and/or sell and/or distribute such content and/or incorporate such content into any form, medium or technology throughout the world without compensation to you.</p>
<p>All content that you submit may be used at our sole discretion. We reserve the right to change, condense or delete any content on any website or social media property that we deem, in our sole discretion, to violate the content guidelines or any other provision of these Terms of Use. We do not guarantee that you will have any recourse to edit or delete any content you have submitted. For the ratings and reviews service, ratings and written comments are generally posted within two to four business days. We reserve the right to remove or to refuse to post any submission for any reason. You acknowledge that you, not LendingTree, are responsible for the contents of your submission. None of the content that you submit shall be subject to any obligation of confidence on the part of us, our agents, subsidiaries, affiliates, partners or third-party service providers and their respective directors, officers and employees.</p>
<p><em>By submitting content or submitting your email address in connection with your rating and review, you agree that LendingTree and its third-party service providers or the entity being reviewed may use your email address to contact you about the status of your review and other administrative purposes.</em></p>
<p><em><span class="tdu">How We Are Compensated</span><br />
	</em><br />
	LendingTree is paid a marketing lead generation fee by Providers for the goods, facilities and services provided. Your use of the Websites and/or LendingTree&#8217;s services constitutes your agreement with this compensation arrangement.
</p>
<p><span class="tdu">Additional Terms Applicable to Specific Financial Services &amp; Products</span></p>
<p>We offer Services that you can use to comparison shop for financial services and products (including, but not limited to, insurance products; commercial Loans; credit cards; mortgage Loans; personal Loans; student Loans; automobile, boat, rv, and watercraft Loans; credit repair products; debt relief services; deposit accounts).</p>
<p>When you complete a Qualification Form, by clicking on any button indicating an acceptance, acknowledgement or agreement to terms, a continuance of processing or submission (collectively, a &#8220;submission&#8221;) you understand that you are consenting, acknowledging and agreeing to the stated terms and conditions of that submission and that you are submitting an inquiry as to a financial service or product through LendingTree which will match you to Providers to whom your request and personal information is transmitted. We may also try to find you matches for similar or alternative Services based on your request. For example, if you sought an unsecured personal Loan, we may present to you an unsecured line of credit if such a product is available in the jurisdiction where you reside.</p>
<p><em><span class="tdu">Terms Applicable to Commercial Loan Requests</span><br />
	</em><br />
	LendingTree’s commercial Loan Websites and Services, including those Services available through SnapCap.com, are designed for businesses and are not intended for individuals’ personal, family or household use. Accordingly, we treat all personal information collected for commercial Loan products, including information about any visitors to our website, as pertaining to individuals acting as business representatives, rather than in their personal capacity.
</p>
<p><span class="tdu"><em>Terms Applicable to Auto Loan Request Services</em></span></p>
<p><strong>By providing a Qualification Form, you are consenting, acknowledging and agreeing to a hard pull of credit by up to five (5) Providers in relationship to your automobile Loan inquiry. You are providing Written Consent for such inquiries and these inquiries may negatively impact your credit score.</strong> If you request an auto Loan and qualify for the Dealer Referral Program, we may also provide your information to one or more of the Providers or third-party marketing companies in that program. The Dealer Referral Program allows you to get financing quotes from a dealership in your area; currently, Car.com, CarLoan.com and Autobytel participate in the program. In addition, you may be matched with one or more Providers offering Loans with which you could finance your automobile.</p>
<p><em><span class="tdu">Terms Applicable to Credit Repair Services</span><br />
	</em><br />
	LendingTree’s affiliate, Ovation Credit Services, Inc. provides credit repair services in exchange for fees which you are responsible for paying only after Ovation has performed its services for the covered period of time. If you enter into an agreement to receive credit repair services from Ovation, then the terms of such service will be defined in the written agreement that you enter into with Ovation.
</p>
<p><em><span class="tdu">Terms Applicable to Insurance Request Services</span><br />
	</em><br />
	LendingTree and its affiliates and subsidiaries, including QuoteWizard.com, LLC (“QuoteWizard”), are not licensed insurance agencies or brokers and do not provide insurance quotes in accordance with RCW 48.17 or similar state statutes. The information we provide is not intended to take the place of professional advice from a licensed insurance agent nor do we provide any evaluation of the insurance providers or their policies. We recommend that all consumers consult with a licensed insurance agent before purchasing any insurance policy. We do not sell any insurance or bind coverage on our Websites; instead, we provide a service to help Providers offer for sale and sell insurance and other authorized products to you.
</p>
<p><span class="tdu"><em>Terms Applicable to Mortgage Loan Request Services</em></span></p>
<p>We provide multiple mortgage request services that you can use to comparison shop for mortgage products. The first option offers you the option to complete a Qualification Form by providing your Social Security Number (“SSN”) along with other information on the Qualification Form. There is a subset of Providers on the LendingTree network that may need your SSN to make a conditional offer. The second option does not require you to provide your SSN. There is a subset of Providers on the LendingTree network that prefer to take leads without an SSN. To use either service, you must provide the information requested on the form, agree to the full Electronic Consent, this Agreement, the Privacy Policy, and any additional terms that are included in the individual form you complete.</p>
<p>LendingTree empowers consumers to comparison shop for mortgage products and is licensed as a Mortgage Broker in all 50 states and the District of Columbia. <strong>LendingTree DOES NOT take formal mortgage applications as defined under applicable state laws, the Equal Credit Opportunity Act, the Truth In Lending Act (“TILA”), and the Real Estate Settlement Procedures Act (“RESPA”). LendingTree is not a lender or a creditor.</strong> LendingTree DOES NOT originate Loans or make credit decisions in connection with Loans, nor does LendingTree issue commitments or lock-in agreements. LendingTree’s services are only administrative. Any Qualification Form you submit is NOT an application for credit. Rather, it is an inquiry to be matched with Providers that may be able to present conditional offers. You will have to complete a formal application with the Provider you choose before the Provider will extend an unconditional offer.</p>
<p>If you close a Loan with a Provider, you will be responsible for paying for any settlement services or closing costs associated with your Loan (such as Loan processing, underwriting, funding fees, appraisals, title insurance premiums, attorney and notary fees, etc.). The Provider, not LendingTree, and the settlement service providers you select will determine the amount of any such fees. Unless expressly stated in writing, nothing contained herein shall constitute an offer or promise for a Loan commitment or interest rate lock-in agreement. The Websites and the Services provided by LendingTree are available in connection with Loans made on real property located in the fifty states and the District of Columbia unless otherwise specified. Providers may not offer all products as well as not offer products in all states.</p>
<p>You might not be matched with any specific Providers making any specific offers. We will continue to attempt to match you for up to twenty-four hours after you submit your request and may contact you via telephone at the number you provided to attempt to help you obtain a match. If we are able to identify a match not originally identified on your online offers page, you agree we may call or contact you to identify such Providers and you may elect to be connected with those Providers to learn more about their products and services. LendingTree cannot and will not select a Provider for you.</p>
<p>When you complete a Qualification Form online, by clicking on any button indicating an acceptance, acknowledgement or agreement to terms, a continuance of processing or submission you understand that you are consenting, acknowledging and agreeing to the stated terms and conditions of that submission and that you are submitting an inquiry as to a product to which LendingTree will match you with Providers to whom your Qualification Form data and personal information is transmitted. LendingTree will also try to find you matches for similar products for which you sought as well as alternative products that may be suitable for your financial needs. For example, if you sought a home equity Loan or home equity line of credit but are also over the age of 62 then LendingTree may present to you a reverse mortgage Provider for a Home Equity Conversion Mortgage.</p>
<p><em><span class="tdu">Terms Applicable to Loan Explorer and Rate Table Products</span></em></p>
<p>LendingTree’s Loan Explorer allows you to view sample rates and contact Providers directly to inquire about their products and services without submitting a Qualification Form. LendingTree’s rate table service enables you to see preliminary offers from Providers with whom you have been matched based on information you provide in a Qualification Form. When using the rate table experience, which may be referred to as Rulo, you will have the opportunity to select Providers to request additional information about their products and services. You may see offers from multiple Providers and there is no restriction on how many Providers you choose to contact.</p>
<p><span class="tdu"><em>Terms Applicable to Student Loan Request Services</em></span></p>
<p>Private student Loans offered by Providers through the Websites do not require school certification and the proceeds are disbursed in the form of a check mailed directly to you, or if more than one person, the person with the stronger credit profile. The proceeds of your Loan must be used for educational purposes.</p>
<p>All Loans are subject to credit approval. Interest rates and Loan fees vary and are based upon borrower and/or cosigner (where applicable), credit score and other underwriting criteria. Approval and underwriting criteria standards are established and maintained solely by the individual Provider(s) and not by LendingTree.</p>
<p>When Providers receive your Loan request, they are not agreeing to lend you money and there will not be such an agreement until the time that the Loan is actually disbursed to you. Providers have the right to accept or reject your cosigner and lend an amount less than the amount requested.</p>
<p>In addition, by submitting your Loan request, you authorize the Providers to verify the accuracy and authenticity of all information supplied by you both internally and with the assistance of non-affiliated third parties. Specifically, you authorize the Providers to verify your enrollment status with your school and other organizations and to verify your employment status by contacting your employer. Providers may also verify any income information that you provide. In all cases, Providers may disclose the fact that you are applying for credit from that Provider.</p>
<p><span class="tdu"><em>Terms Applicable to My LendingTree</em></span></p>
<p>By creating a My LendingTree account (whether directly or in conjunction with submitting a Qualification Form), you understand and consent to LendingTree receiving and accessing consumer report information about you from one or more credit bureaus. By registering with My LendingTree, you are providing express written instructions under the federal Fair Credit Reporting Act <strong>that we may use and analyze your information as follows: to (a) present you an overview of your credit profile including detailed information where available; (b) provide you with customized recommendations and general information about you; and/or (c) serve you targeted ads and other communications based on your information, (d)identify affiliate and non-affiliate Providers that may be able to provide valuable services to you; (e) so that LendingTree may perform analysis and data modeling in order to offer customers better Services in the future.</strong> This information could include, but might not be limited to, your credit report, credit score, and other credit information. For as long as you maintain a My LendingTree account, you are providing express written consent for us to maintain and share information provided by you, and about you by third parties, to assist with litigation, regulatory request(s), law enforcement requests, internal analytics, marketing purposes, and any other legally permissible purpose.</p>
<p><span class="tdu"><em>Terms Applicable to Realty Services</em></span></p>
<p>By clicking on any button indicating an acceptance or agreement to terms, a continuance of processing or submission (collectively, a &#8220;submission&#8221;), including any submission made in connection with a Qualification Form for other LendingTree products or services on which you indicate your desire to be connected with a real estate company, you understand that you are agreeing to the stated terms and conditions of that submission and that you are submitting an inquiry to LendingTree and its network of real estate companies, brokers, and agents (&#8220;Real Estate Companies&#8221;). You authorize LendingTree to forward your information to the Real Estate Companies. You further understand and agree that by selecting a Real Estate Company or other provider, you are providing express written consent for them to contact you by telephone at the numbers (whether landline or cellular) you have provided, including for marketing purposes, and you hereby consent to any such calls even if your phone number is on the Do Not Call list.</p>
<p><em><span class="tdu">Widgets</span></em></p>
<p>Generally, widgets are tools that you may place on your website, which allow visitors to your website to access and view content on or from another website. Widgets published by LendingTree (“Widgets”) provide access to the Websites, Content and Services from points outside of the Websites. Widgets may be placed on your websites, blogs, your pages at online social network or media sites (to the extent permitted by such sites), and other similar platforms. LendingTree prohibits the placement of Widgets on websites, platforms or devices that contain content that is sexual, offensive, deceptive or illegal in nature or that in any way promotes or encourages hatred, violence, discrimination or illegal activities, or otherwise inappropriate as determined by LendingTree in its sole discretion. You shall use the Widgets in a manner consistent with all applicable laws and solely for lawful purposes. You cannot use the Widgets for any other purpose, and nothing in this Agreement shall be deemed to grant you any rights, title or interest in the Widgets, Websites, Content or Services. LendingTree reserves the right to remove or demand the removal of any Widget, or revoke your right to use any Widget, for any reason.</p>
<p>By accessing and using any Widget (including copying any Widget html code), you agree to be bound by the following:</p>
<ol>
	<li>You may only display the Widget(s) on a website you own and operate and not in any other manner or in any other medium.</li>
	<li>You may not modify any Widget. Without limitation, you may not change any code provided by LendingTree, obscure or disable any element of any Widget, tag links to LendingTree from the Widget with a &#8220;nofollow&#8221; attribute or otherwise prevent or discourage search engines from following or scoring link.</li>
	<li>Except for displaying the Widget, you agree not to make any representations, warranties (express or implied) or other statements concerning LendingTree, our Websites, Services, and Providers.</li>
	<li>You may not display any Widget in any manner that implies affiliation with, sponsorship or endorsement by LendingTree.</li>
	<li>You must place the Widget on a page that is context-appropriate to the content of the Widget, and any reference to LendingTree or its products and services must be accurate. For example, you may place Widgets on pages of your web site that contain a discussion of personal finance, mortgages or residential real estate.</li>
	<li>You may not place the Widget on any site that contains any content that is in any way unlawful, harmful, obscene, harassing, or racially, ethnically, or otherwise objectionable.Additionally, you may not place the Widget on any site that disparages LendingTree, our Services, or the products/services of Providers on our network, infringes any LendingTree intellectual property or other rights, or violates any applicable law.</li>
	<li>LendingTree grants you a non-transferable, non-exclusive, revocable right to download/display the Widget solely in accordance with (i) the terms of this Agreement and (ii) solely in connection with the Widget, to use our logos, trademarks, trade names and other intellectual property contained in the Widget. This Agreement does not grant you any right in any LendingTree code, content, logos or trademarks beyond the limited permission to display the Widget granted herein. LendingTree reserves the right at any time to terminate or modify your permission to display the Widget. The Widgets are subject to change from time to time in our sole discretion. We may cease to return content from the Widget at any time in our sole discretion.</li>
	<li>You acknowledge and agree that LendingTree may crawl or otherwise monitor your web site to confirm compliance with this Agreement.</li>
	<li>The Widget and any information, software, and related services are provided &#8220;as is&#8221; with no warranty, and LendingTree expressly disclaims any warranties that may be expressed or implied by law regarding any Widget, including warranties of accuracy or non-infringement. Use of Widgets is at your own risk. LendingTree is not liable for any direct, indirect, punitive, incidental, special or consequential damages or other injury arising out of or in any way connected with the use of any Widget whether resulting in whole or in part, from breach of contract, tortious behavior, negligence, strict liability or otherwise.</li>
	<li>LendingTree reserves the right to change this Agreement in its sole discretion at any time without notice, and you are responsible for regularly reviewing this Agreement. Your continued use of any Widget after the effective date of such changes will constitute acceptance of, and agreement to, any such changes.</li>
</ol>



				</div><!-- END of .container -->
			</div><!-- END of .box-wr -->



		</div><!-- END of .content -->

<?php include 'includes/footer.php'; ?>
